FROM node:6
USER root

COPY . /opt/crashalert
RUN cd /opt/crashalert ; \
    npm install

ENV TWITTER_CONSUMER_KEY=$TWITTER_CONSUMER_KEY \
    TWITTER_CONSUMER_SECRET=$TWITTER_CONSUMER_SECRET \
    TWITTER_ACCESS_TOKEN=$TWITTER_ACCESS_TOKEN \
    TWITTER_ACCESS_KEY=$TWITTER_ACCESS_KEY \
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    CRASHALERT_EMAIL_FROM=$CRASHALERT_EMAIL_FROM \
    CRASHALERT_EMAIL_TO=$CRASHALERT_EMAIL_TO

WORKDIR    /opt/crashalert
ENTRYPOINT ["/bin/bash"]
