FROM node:6
USER root

COPY . /opt/crashalert
RUN cd /opt/crashalert ; \
    ls

ENV TWITTER_CONSUMER_KEY=$TWITTER_CONSUMER_KEY \
    TWITTER_CONSUMER_SECRET=$TWITTER_CONSUMER_SECRET \
    TWITTER_ACCESS_TOKEN=$TWITTER_ACCESS_TOKEN \
    TWITTER_ACCESS_KEY=$TWITTER_ACCESS_KEY

WORKDIR    /opt/crashalert
ENTRYPOINT ["/bin/bash"]
